all:
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ~/.ssh/homelab_k8s
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
    ansible_python_interpreter: /usr/bin/python3

  children:
    # Kubespray groups
    kube_control_plane:
      hosts:
        k8s-master:
          ansible_host: 192.168.122.10

    kube_node:
      hosts:
        k8s-worker-1:
          ansible_host: 192.168.122.11
        k8s-worker-2:
          ansible_host: 192.168.122.12

    etcd:
      hosts:
        k8s-master:
          ansible_host: 192.168.122.10

    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:

    calico_rr:
      hosts: {}
