# Add this at the top level (outside server {})
map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      close;
}

server {
    listen ${HEADLAMP_PROXY_PORT};
    server_name _;

    # Required for resolving variables in proxy_pass (like $gitlablurl)
    resolver 127.0.0.53 valid=30s;

    # location / {
    #     proxy_pass http://${HEADLAMP_INGRESS_HOSTNAME}/;
    #     proxy_set_header Host ${HEADLAMP_INGRESS_HOSTNAME};
        
    #     # Identity headers
    #     proxy_connect_timeout 5s;
    #     proxy_set_header X-Real-IP $remote_addr;
    #     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    #     proxy_set_header X-Forwarded-Proto $scheme;

    #     # WebSocket headers - The "Clean" way
    #     proxy_http_version 1.1;
    #     proxy_set_header Upgrade $http_upgrade;
    #     proxy_set_header Connection $connection_upgrade; # Uses the map above

    #     # Timeouts for logs
    #     proxy_read_timeout 3600s;
    #     proxy_send_timeout 3600s;
    #     proxy_buffering off; # Disable buffering so logs stream instantly
    # }

    location ~^/(.+) {
        # Define the internal destination
        set $backend_ip "192.168.122.200";

        # This takes the captured part (e.g., vportal.se.app1) 
        # and sets it as the Host header for the backend
        proxy_set_header Host $1;

        # Standard headers to ensure the backend sees the real client info
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # Proxy pass to your cluster IP
        proxy_pass http://$backend_ip;
    }

    
}