server {
    listen ${HEADLAMP_PROXY_PORT};
    server_name localhost; # Listen on localhost for Tailscale to pick up

    location / {
        proxy_pass http://${HEADLAMP_INGRESS_HOSTNAME};
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # WebSocket support for Headlamp
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}